# Básicos
listen_addresses = '*'
max_connections = 200

# Logical replication
wal_level = logical
max_wal_senders = 20
max_replication_slots = 20
wal_keep_size = 256MB
archive_mode = on
archive_command = 'pgbackrest --stanza=master1 archive-push %p'

# Rendimiento prudente
shared_buffers = 512MB
effective_cache_size = 1GB
maintenance_work_mem = 64MB
work_mem = 8MB

# Seguridad sencilla de demo
password_encryption = scram-sha-256
