# Host de tu API
host=http://localhost:3000

# Número de usuarios simulados y velocidad de arranque
users=1
spawn-rate=1

# Tiempo de ejecución (puedes ajustar)
run-time=1m
headless=true

# Reportes
html=report.html
csv=report